### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jlconlin**
Adding a few instructions for how to update NJOY.

### CODE REVIEW

**Comment by whaeck** [comment]
At some point, we should add an overview of configuration options for NJOY2016 (e.g. flag to change installation directory, static executable, etc.). But that is not important for the moment.

**Comment by whaeck** [comment]
We should maybe add the 'make install' step as well. I saw Ionel do this last week.

**Comment by jlconlin** [comment]
Yes, this does need an update. It's been on the back burner as we try to finish out the resonance reconstruction.

**Review by whaeck — APPROVED** [review]
No objections.

**Pull request merged**
